import { IProduct, IManufacturer } from './constants/interfaces'

const manufacturers: IManufacturer[] = [
  { id: '1', name: 'ElectroTech Innovations' },
  { id: '2', name: 'GreenLiving Solutions' },
  { id: '3', name: 'FutureTech Innovators' },
  { id: '4', name: 'InnovateTech Systems' },
  { id: '5', name: 'HealthTech Solutions' },
]

const pharmacyProducts: IProduct[] = [
  {
    id: '1',
    name: 'PainRelief X1',
    manufacturer: manufacturers[0],
    price: 15.99,
    expiryDate: new Date('2023-12-31'),
  },
  {
    id: '2',
    name: 'EcoVitamin Pro',
    manufacturer: manufacturers[1],
    price: 9.99,
    expiryDate: new Date('2023-11-30'),
  },
  {
    id: '3',
    name: 'SmartMed Assistant',
    manufacturer: manufacturers[2],
    price: 25.99,
    expiryDate: new Date('2024-02-28'),
  },
  {
    id: '4',
    name: 'GizmoReliever Plus',
    manufacturer: manufacturers[3],
    price: 29.99,
    expiryDate: new Date('2023-10-15'),
  },
  {
    id: '5',
    name: 'UltraHealth Tracker',
    manufacturer: manufacturers[4],
    price: 19.99,
    expiryDate: new Date('2023-09-30'),
  },
  {
    id: '6',
    name: 'LifeBoost Capsules',
    manufacturer: manufacturers[0],
    price: 12.99,
    expiryDate: new Date('2023-11-15'),
  },
  {
    id: '7',
    name: 'GreenLife Respirator',
    manufacturer: manufacturers[1],
    price: 34.99,
    expiryDate: new Date('2024-01-31'),
  },
  {
    id: '8',
    name: 'FutureVision Glasses',
    manufacturer: manufacturers[2],
    price: 45.99,
    expiryDate: new Date('2023-12-15'),
  },
  {
    id: '9',
    name: 'InnovateSmart Thermometer',
    manufacturer: manufacturers[3],
    price: 22.99,
    expiryDate: new Date('2023-10-30'),
  },
  {
    id: '10',
    name: 'HealthTrack Pulse Oximeter',
    manufacturer: manufacturers[4],
    price: 18.99,
    expiryDate: new Date('2023-11-30'),
  },
  {
    id: '11',
    name: 'ElectroTech Power Bank',
    manufacturer: manufacturers[0],
    price: 39.99,
    expiryDate: new Date('2023-09-15'),
  },
  {
    id: '12',
    name: 'GreenLiving Eco Bag',
    manufacturer: manufacturers[1],
    price: 9.99,
    expiryDate: new Date('2024-03-31'),
  },
  {
    id: '13',
    name: 'FutureTech Smart Mirror',
    manufacturer: manufacturers[2],
    price: 55.99,
    expiryDate: new Date('2023-08-31'),
  },
  {
    id: '14',
    name: 'InnovateTech GPS Tracker',
    manufacturer: manufacturers[3],
    price: 27.99,
    expiryDate: new Date('2023-10-15'),
  },
  {
    id: '15',
    name: 'HealthTech Blood Pressure Monitor',
    manufacturer: manufacturers[4],
    price: 32.99,
    expiryDate: new Date('2023-12-31'),
  },
  {
    id: '16',
    name: 'ElectroTech Wi-Fi Router',
    manufacturer: manufacturers[0],
    price: 89.99,
    expiryDate: new Date('2023-11-30'),
  },
  {
    id: '17',
    name: 'GreenLiving Bamboo Toothbrush',
    manufacturer: manufacturers[1],
    price: 4.99,
    expiryDate: new Date('2024-02-28'),
  },
  {
    id: '18',
    name: 'FutureTech Virtual Keyboard',
    manufacturer: manufacturers[2],
    price: 65.99,
    expiryDate: new Date('2023-10-15'),
  },
  {
    id: '19',
    name: 'InnovateTech Smart Refrigerator',
    manufacturer: manufacturers[3],
    price: 100.99,
    expiryDate: new Date('2023-09-30'),
  },
  {
    id: '20',
    name: 'HealthTech Stress Relief Massager',
    manufacturer: manufacturers[4],
    price: 24.99,
    expiryDate: new Date('2023-11-15'),
  },
  {
    id: '21',
    name: 'PainRelief Patches',
    manufacturer: manufacturers[0],
    price: 8.99,
    expiryDate: new Date('2024-04-30'),
  },
  {
    id: '22',
    name: 'EcoVitamin D3 Supplement',
    manufacturer: manufacturers[1],
    price: 14.99,
    expiryDate: new Date('2024-03-15'),
  },
  {
    id: '23',
    name: 'SmartMed Sleep Aid',
    manufacturer: manufacturers[2],
    price: 19.99,
    expiryDate: new Date('2024-05-31'),
  },
  {
    id: '24',
    name: 'GizmoReliever Gel',
    manufacturer: manufacturers[3],
    price: 11.99,
    expiryDate: new Date('2024-01-15'),
  },
  {
    id: '25',
    name: 'UltraHealth Immunity Booster',
    manufacturer: manufacturers[4],
    price: 29.99,
    expiryDate: new Date('2023-12-01'),
  },
]

export { pharmacyProducts, manufacturers }
